version: "3.8"

services: 
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      driver: none
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    command: redis-server
    volumes:
      - redis:/data
    logging:
      driver: none
    ports:
      - "6379:6379"

  web:
    build: ../
    container_name: rails_app
    command: bundle exec rails s -p 3000 -b -e development -b '0.0.0.0'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecs_application_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BUNDLE_PATH: /bundle
    volumes:
      - ../:/rails-app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
  
  sidekiq:
    build: ../
    command: bundle exec sidekiq
    volumes:
      - ../:/rails-app
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "redis"

      
volumes:
  db:
  bundle:
  redis: